version: '3.8'

services:
  spring-ci-cd:
    container_name: spring-ci-cd
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge