name: Spring Boot CI/CD github

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar

  deploy:
    runs-on: self-hosted
    steps:
      - name: Stop existing containers
        run: |
          docker-compose down

      - name: Build and run Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d --build